---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vaultwarden-backup-job
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vaultwarden-backup-job
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: &name vaultwarden-backup-job
subjects:
  - kind: ServiceAccount
    name: *name
roleRef:
  kind: Role
  name: *name
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-backup-job
data:
  backup.sh: |
    #!/bin/sh

    TIMESTAMP=$(TZ="${TIMEZONE}" date +"%Y-%m-%d_%H-%M-%S")
    TARGET_ARCHIVE="export-$${TIMESTAMP}.zip"

    echo "starting vaultwarden backup $${TARGET_ARCHIVE}"
    # apt-get update && apt-get install -y sqlite3
    zip -9 -r "/mnt/backup/$${TARGET_ARCHIVE}" /mnt/vw-data*
    echo "finished vaultwarden backup"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vaultwarden-backup
spec:
  schedule: "30 3 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 60
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          serviceAccount: vaultwarden-backup-job
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: vaultwarden
                  topologyKey: kubernetes.io/hostname
          containers:
            - name: backup
              image: debian:bookworm-slim
              command: ["sh", "-c", "/scripts/backup.sh"]
              volumeMounts:
                - name: vw-data
                  mountPath: /mnt/vw-data
                - name: backup-nfs
                  mountPath: /mnt/backup
                - name: script-volume
                  mountPath: /scripts/backup.sh
                  subPath: backup.sh
          restartPolicy: OnFailure
          volumes:
            - name: vw-data
              persistentVolumeClaim:
                claimName: vaultwarden
                readOnly: true
            - name: backup-nfs
              persistentVolumeClaim:
                claimName: backup-nfs-${APP}
            - name: script-volume
              configMap:
                name: vaultwarden-backup-job
                items:
                  - key: backup.sh
                    path: backup.sh
                defaultMode: 0555 # read and execute
