apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:wgBqJIXQpqPkBkfJYut+3EYQfvTiawmmABbWuBZBfW/wRzE9nahqnV2v/g20SDQLuKndYlN/lgSGLBMiw3lRi1E64pD55GRcc7/Opk9e5CnpxtSufJKSFlkVMGE+ohq0Tz1IkVVB35th0HaMW8vQjemoosMalxoqWJd/S+k+zmtT1ukbnh0=,iv:SDlBy+f4GvvLyJXwM6EZ4+JXTO5lIN0ptm3vNMzjV5U=,tag:HgFi807+TqOwZj9BIqI97Q==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:q/SYN+xrcY7i6QYvkSK8qvuGSA==,iv:wsTNBlrZRrksoaoBWvstnG+4A0HUEc0WYm0dCii0IRY=,tag:j+y8hyqSTojV9PThSkClug==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:iTMGyNoUECMauYHX7eHHCrRfNw==,iv:qG1LnipfvkAd4P8TGaFIbv6W0BummtLh7LZxpU2kD10=,tag:WZHZEz3G1AQ+/blUrJNVqw==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:iiada3X/95kpMzHZEptb4g==,iv:nU8sTWJo9H2JSOfnI/+RdGjiuBTcgvMWT7zleu+VugY=,tag:5Uv5K0AxvTSkayjqMpG2Lw==,type:str]
sops:
  lastmodified: "2025-11-01T18:25:36Z"
  mac: ENC[AES256_GCM,data:m5fcOHWBqs338H34Cgd7q2NJfti6LyQ9ehwNC7dq9CHqk8YYaLjRfPrcL01kMNifVgBmXN4afqfyxT/wYW5wBaW1S7MNczfSn5RgmZFXbjr06Jr8RUhrFJDhK0mSfEOsxV8/rPZLSZEQNGQVusp+vIIYbDlYFw909O67yKspfSU=,iv:b/2XAFgAHTXTAe8nqj3t7dacRZkT/KJGALutBLyOcYQ=,tag:hiL3Oq0C1IXOChafqA3ryw==,type:str]
  pgp:
    - created_at: "2025-08-12T14:08:37Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAjJO1d0laKZOvpdXRf8OGGK8ZI5XEPfUQaZ916rCuQdv1
        aOuonuJSEMoUQyJ1L3mogR5R3GijZeTz4PtILSPhmGoBtd4SDhoXE1xdk00dQQ2c
        YVRBegnBSi2+ofaCU2oZvwiM5Ut5TcmsB3DewNuFsa8GMh/OSDyru/dbPm7A/WQc
        /67/OunSn939yvaLvN7U7MGyJdlZnAdtf9+vhifFJWOfvbmcwV6cpkg2bSczSdwc
        bGn3S2O90wv4AgSACyf1QgfmqenRhQoQy3GrFC8Uco5F46QPRz/lOhbdm7aWw1IB
        dIEF7RIZ2Efyswl8oQXxRkOlTuFV3sCbxRTD+POeW4OmyWO/326JAnmRUzU35bQL
        ISp+Db7X5dpJ9Gn9E47ze/dYqnltfHcjGZzFV836/OgvLA4Tu9uYxNplXnA0MGFu
        25X+deN0HxRTil2YyWsvPHjwWPwlOV9ab7119zKwAatTQkIPt3xBpXjiOmDCO5Xd
        BAJWxgJY66ns9kXqbP73jP6NbKXLSM8Uju12+NIkogD3F6gtOSDnw34soCVT5/p8
        dPqXPXHIdaDT6ASSZPoHW8IGIxQMwqNZjZcW8czHvzSn8k7sjwO5kDewQmb+xFBG
        WTVU45ZmYO4cnuj39IcFTl9Eb7bvZ32DWb250KVqAaUTEWarO3tdVxwTQFA2nSLS
        XAGMPRcOnhlNRI2ZmfFtl7irro3fC56SHgav1/ApcSMb+UpL7QbalTcKbwEkOZcl
        mmPYFP2YjdCHqAGCmLoF4WljYS6cGTFFYqqkaiW8VkygxEV2K/0W6DO2Gvxa
        =uMlZ
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
