flux_github_token: ENC[AES256_GCM,data:HjUuOZhAaoJRgdIA4tMHFHPwco2xl/1lT4nYrUO1Ho3mb3sDLTb4rc8kyso7W+63iJUsMDZDoOdWmylClXlphWnBThlixsLLxJHF863/H+VFEe4miA/2zMx9bveO,iv:cHrG8pnrnuIKCUtq7m5tDFhELnXkifrgZBvN54t8Xj8=,tag:A36+EE3hmH2qNZB+7Nll1w==,type:str]
sops:
    lastmodified: "2026-01-01T11:43:27Z"
    mac: ENC[AES256_GCM,data:6r5JiAFClBVcJLGYHwEB946KWWZuz2wi1kwobfB8pezwEsMdDwI6On6cXysvJiy01ls4fKtPT06RRzcWNO5+FUaEgz3jy2gLdbl71KJZ1vpp+cwq/anGoncAguTaXSkZLFkcJGlH0wioVq65hk1nkbWzqV4F7cPSF5JA2q/a82s=,iv:BWAIn/XMSjS4EWGYfQDSTlKV6df3zRGGGn+0kaY5ikw=,tag:Wv9yS2O8KTvtaUpVayzCdw==,type:str]
    pgp:
        - created_at: "2025-08-24T11:27:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA06fffInlMOLAQ//ROvyHRt1toXlpepoZIgv0AvSkFIF0EMojkyqv2Mvr5cT
            SrRoPDd3XACBzFclK9sSaMCVRjKeIhAT7btmV1mVt6viYrbihutYHmAEDfHyMqA7
            HaixUoPUSG68EEBOl1ROranoA3WKMTe/EcZ34C5m2jIN7Ei5rP3zUeOX6xYipLvI
            k4JOxtrx4IRc0EQBqZZLNCxrXvN47Bwjvccwixn07gwn5s7oWwFjrtsKC/oOi6fC
            JDudy7OghSlf/Qe6LhV5LhvzTX7aQ0cnIVbvzt1ZzNDxw6KUFhnh5SPXnop2fo+Q
            JGisKQH42fRPUqSKBZJjkLYthnGxGbWT/zL1Axqsgw+o+C6ppREKHX5f/wesxImT
            2VXCYKXdhq7C9WsfjoOWFLt5vbEb9WE0J5kpdYC/IIAAH2+VmF1d8G4Q6W+w65fq
            kcNozY0/6EJzcPWw08oknH3QdOk4/SMByDlLap4vJfbEjMYO9aGq6R0uFq8xQNpT
            UtSJfhUXSsJdGL6YtnkfFdy+yGUwF0XH/LPjBl8O43dpbNYDc1PpxAmFIuMPMRHK
            ymlrViYt4SHduePFTr6+T14z11g1VSgrF5Xa2pzA5ZH7FqkhKS0TEcBuG7NxB1YP
            PFU8F1yTrpMv/J0BRkaHqse3oQbfH2NBmDdVp2jfoKz8rEx4vZSvajD9v7TXQS7S
            XgHKPxJPQyQ4R0ukfSZnpYhiv5PktQLxDS1i059G3o1HOq+gaf46Z5B08ih3hmU/
            ODd+E2tInVTAQTSgQ4QbhdtlS/8eesVWBaa9Y/nvZx3qgrO9J1lETjLNMEuK1BQ=
            =jGAd
            -----END PGP MESSAGE-----
          fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
    unencrypted_suffix: _unencrypted
    version: 3.11.0
