---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mathesar-db
  namespace: flux-system
spec:
  targetNamespace: default
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/prod/default/mathesar/db
  prune: true
  wait: true
  dependsOn:
    - name: rook-ceph-cluster
      namespace: flux-system
    - name: cloudnative-pg-operator
      namespace: flux-system
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname mathesar
  namespace: flux-system
spec:
  targetNamespace: default
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/prod/default/mathesar/app
  prune: true
  wait: true
  dependsOn:
    - name: rook-ceph-cluster
      namespace: flux-system
    - name: mathesar-db
      namespace: flux-system
  postBuild:
    substitute:
      APP: *appname
