apiVersion: v1
kind: Secret
metadata:
  name: postgres-mathesar-superuser
stringData:
  username: ENC[AES256_GCM,data:G+Vq6tYrXmA=,iv:OdwIrqbtv6McVK2ENWdSvHwzr+9GeCJ1yr1V5os9YAo=,tag:bxLbcYjwmuAbvMmEhdKy8Q==,type:str]
  password: ENC[AES256_GCM,data:8eRM6/GaHqbOeqzy4gtZuXVNYdrLVz1PFafpwWCpo8U=,iv:qg5cO/WiNoFmA51VkaCyH96Ck4bipVOc9sMCHiv+2TY=,tag:LVz7Ry/EbthQr1AETeEy7A==,type:str]
sops:
  lastmodified: "2025-11-11T11:36:22Z"
  mac: ENC[AES256_GCM,data:9ZbnCQBKvCZ3VOprDeitx1zXJNFJDknu3ogr2wQ4dvHLjNlP8rhAHy/0O+pIad4b4fKSHWxScBKmsAts5//NPqYGWfBknSWqxQ4Br6FFo/k18y9y6i26jaFfvPcwg1NdUBgGTZ8l+zw1eRQ1JxMm2NJoAWuVpp24lNbIQQxEZqQ=,iv:0J7HNzgXPxHR1N5F+I08PQ/shPBST5v2hiqKUuh/lEo=,tag:pGN4qGhFpxn1f95RjvyfEA==,type:str]
  pgp:
    - created_at: "2025-08-12T14:08:37Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAjJO1d0laKZOvpdXRf8OGGK8ZI5XEPfUQaZ916rCuQdv1
        aOuonuJSEMoUQyJ1L3mogR5R3GijZeTz4PtILSPhmGoBtd4SDhoXE1xdk00dQQ2c
        YVRBegnBSi2+ofaCU2oZvwiM5Ut5TcmsB3DewNuFsa8GMh/OSDyru/dbPm7A/WQc
        /67/OunSn939yvaLvN7U7MGyJdlZnAdtf9+vhifFJWOfvbmcwV6cpkg2bSczSdwc
        bGn3S2O90wv4AgSACyf1QgfmqenRhQoQy3GrFC8Uco5F46QPRz/lOhbdm7aWw1IB
        dIEF7RIZ2Efyswl8oQXxRkOlTuFV3sCbxRTD+POeW4OmyWO/326JAnmRUzU35bQL
        ISp+Db7X5dpJ9Gn9E47ze/dYqnltfHcjGZzFV836/OgvLA4Tu9uYxNplXnA0MGFu
        25X+deN0HxRTil2YyWsvPHjwWPwlOV9ab7119zKwAatTQkIPt3xBpXjiOmDCO5Xd
        BAJWxgJY66ns9kXqbP73jP6NbKXLSM8Uju12+NIkogD3F6gtOSDnw34soCVT5/p8
        dPqXPXHIdaDT6ASSZPoHW8IGIxQMwqNZjZcW8czHvzSn8k7sjwO5kDewQmb+xFBG
        WTVU45ZmYO4cnuj39IcFTl9Eb7bvZ32DWb250KVqAaUTEWarO3tdVxwTQFA2nSLS
        XAGMPRcOnhlNRI2ZmfFtl7irro3fC56SHgav1/ApcSMb+UpL7QbalTcKbwEkOZcl
        mmPYFP2YjdCHqAGCmLoF4WljYS6cGTFFYqqkaiW8VkygxEV2K/0W6DO2Gvxa
        =uMlZ
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
