apiVersion: v1
kind: Secret
metadata:
  name: mathesar-secret
stringData:
  sso.yml: ENC[AES256_GCM,data:5AZkiTE+rr5GAGcuY7ERIvoEsbpq3XrGLMUxwFPGBElux3xOweCeFfI3SCNk1dnxzhE+CJpIFEb+3j7UI3KEf6Z+t377P2+b5KC7UH9kAHDIxTpU45XS17cBWhGuU41LwzylgdA9JTzOhfbpFK961izce2ciHhaPv/qmR8yUut3rQdBkTfp2r8LU8ZUdrRsI+eaMOVar0WPNQ9jnxN0Xnrl+18EcXHk7NOx9A/4bwGYp06t3dmrKoF+e5MF3cDK0/wR55UAkiQ==,iv:Z65D8rRijaL1xKg3c7g8Yt8/5jaqLv/YLvKqwrCTR0A=,tag:k9icgqyBrnSWQIzCTWziVA==,type:str]
sops:
  lastmodified: "2025-11-11T12:15:21Z"
  mac: ENC[AES256_GCM,data:vAF/veUAFScdUnesI6M9b3bSHJViD7mJR6Zb3QXbTDK5p6kKZBDETW8YTsHv3ziR8nyPKexh1umasmx+HNBGvsA3s2JdmswZF1GhzHBGjDL2qcEetzVWWwONjXfSqFvpXwhVJGRJ8bc23TttIgDgGfoEpsu8PHz4W1CtRxKti8k=,iv:klk7Ln9uq5+6CVViARrVE6u7NaucSIBXzS2LRFn+vdE=,tag:PQZi9hFma5v+RHqABZ3CVQ==,type:str]
  pgp:
    - created_at: "2025-08-12T14:08:37Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAjJO1d0laKZOvpdXRf8OGGK8ZI5XEPfUQaZ916rCuQdv1
        aOuonuJSEMoUQyJ1L3mogR5R3GijZeTz4PtILSPhmGoBtd4SDhoXE1xdk00dQQ2c
        YVRBegnBSi2+ofaCU2oZvwiM5Ut5TcmsB3DewNuFsa8GMh/OSDyru/dbPm7A/WQc
        /67/OunSn939yvaLvN7U7MGyJdlZnAdtf9+vhifFJWOfvbmcwV6cpkg2bSczSdwc
        bGn3S2O90wv4AgSACyf1QgfmqenRhQoQy3GrFC8Uco5F46QPRz/lOhbdm7aWw1IB
        dIEF7RIZ2Efyswl8oQXxRkOlTuFV3sCbxRTD+POeW4OmyWO/326JAnmRUzU35bQL
        ISp+Db7X5dpJ9Gn9E47ze/dYqnltfHcjGZzFV836/OgvLA4Tu9uYxNplXnA0MGFu
        25X+deN0HxRTil2YyWsvPHjwWPwlOV9ab7119zKwAatTQkIPt3xBpXjiOmDCO5Xd
        BAJWxgJY66ns9kXqbP73jP6NbKXLSM8Uju12+NIkogD3F6gtOSDnw34soCVT5/p8
        dPqXPXHIdaDT6ASSZPoHW8IGIxQMwqNZjZcW8czHvzSn8k7sjwO5kDewQmb+xFBG
        WTVU45ZmYO4cnuj39IcFTl9Eb7bvZ32DWb250KVqAaUTEWarO3tdVxwTQFA2nSLS
        XAGMPRcOnhlNRI2ZmfFtl7irro3fC56SHgav1/ApcSMb+UpL7QbalTcKbwEkOZcl
        mmPYFP2YjdCHqAGCmLoF4WljYS6cGTFFYqqkaiW8VkygxEV2K/0W6DO2Gvxa
        =uMlZ
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
