apiVersion: v1
kind: Secret
metadata:
  name: mathesar-secret
stringData:
  sso.yml: ENC[AES256_GCM,data:HNk4YQ4/EXjC+fyuLCe+uT67/n3Yhrw+za4cY9sYZRxD18XhXR9Wpt0R4IX5pglYblL5vssTHk6UOsZCwVL8t9M9sTIwidYDRKjkMfz6D5aqpm8/9tm/2sGIQaoZuEagZ79Q4NToTRbdel6XLrC3MDR6JogonX/yrtB1Qm9raUJao/BhnOcxekj1YQXN1K8I91kMVtSAY4CwkWSXb/f7A1pimR2l1SVJAdLaRsNBUas6NAcBf7q3fci+iOBtJZo5,iv:5BLELedQg4Tw3v7zvTMetEbRTywQIdaAej8G7ztAoFA=,tag:JoI9jD6sp1nDnT8fZLbOlg==,type:str]
  OIDC_CONFIG_DICT: ENC[AES256_GCM,data:KoG0/miOqjnmz7te7yMb2ZYk162sqWSs/xOYZ8NZ6CpcxFHbbjDHy68NEMGZ3WkFb7E5UdexKP3lFyP73huyyK8PPkFuK4upgq9WxPj4FPDGV7Ve4bg1VN3LmY4kC5msXs2uhbpq5V1IkGI6gKDmsV7JkvrqVe6k9PcrRBsF0k13SRtdvsHXLsgKJkQZUcUhWTSdke9nyKc+S+HyBcC7Ea+T8NHGNvAbOs95b13Z6t4=,iv:ots1qrmJvAe1PoOs6zrBTR0ioNZnfgb5nvtbDYwYwkQ=,tag:e0fKE2Tjla58jw3vx/cTjw==,type:str]
sops:
  lastmodified: "2025-11-11T13:33:39Z"
  mac: ENC[AES256_GCM,data:4WCAEs2RIsFzqeRPkDdOZDcNrBUubw8lJ1bwRK3MEKKVVF5ZwxZsqOI9mYGdpEeADPxAq1zMBfKGpdYaKENJLmQ+OMauqPIQIv8JE4sXQ1I7GgUm21g9Pv2slwnXWQFr+6OP+0D3wTriXDFlUcZy6ZAWwZKrxY3wPrri6Wr1io0=,iv:bmMXpFisCU3+njshmMhDk17cM0Cl1ak21C+tz8UyuME=,tag:Tri7slAEimedlonmiShAJQ==,type:str]
  pgp:
    - created_at: "2025-08-12T14:08:37Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAjJO1d0laKZOvpdXRf8OGGK8ZI5XEPfUQaZ916rCuQdv1
        aOuonuJSEMoUQyJ1L3mogR5R3GijZeTz4PtILSPhmGoBtd4SDhoXE1xdk00dQQ2c
        YVRBegnBSi2+ofaCU2oZvwiM5Ut5TcmsB3DewNuFsa8GMh/OSDyru/dbPm7A/WQc
        /67/OunSn939yvaLvN7U7MGyJdlZnAdtf9+vhifFJWOfvbmcwV6cpkg2bSczSdwc
        bGn3S2O90wv4AgSACyf1QgfmqenRhQoQy3GrFC8Uco5F46QPRz/lOhbdm7aWw1IB
        dIEF7RIZ2Efyswl8oQXxRkOlTuFV3sCbxRTD+POeW4OmyWO/326JAnmRUzU35bQL
        ISp+Db7X5dpJ9Gn9E47ze/dYqnltfHcjGZzFV836/OgvLA4Tu9uYxNplXnA0MGFu
        25X+deN0HxRTil2YyWsvPHjwWPwlOV9ab7119zKwAatTQkIPt3xBpXjiOmDCO5Xd
        BAJWxgJY66ns9kXqbP73jP6NbKXLSM8Uju12+NIkogD3F6gtOSDnw34soCVT5/p8
        dPqXPXHIdaDT6ASSZPoHW8IGIxQMwqNZjZcW8czHvzSn8k7sjwO5kDewQmb+xFBG
        WTVU45ZmYO4cnuj39IcFTl9Eb7bvZ32DWb250KVqAaUTEWarO3tdVxwTQFA2nSLS
        XAGMPRcOnhlNRI2ZmfFtl7irro3fC56SHgav1/ApcSMb+UpL7QbalTcKbwEkOZcl
        mmPYFP2YjdCHqAGCmLoF4WljYS6cGTFFYqqkaiW8VkygxEV2K/0W6DO2Gvxa
        =uMlZ
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
