apiVersion: v1
kind: Secret
metadata:
  name: mathesar-secret
stringData:
  sso.yml: ENC[AES256_GCM,data:HNk4YQ4/EXjC+fyuLCe+uT67/n3Yhrw+za4cY9sYZRxD18XhXR9Wpt0R4IX5pglYblL5vssTHk6UOsZCwVL8t9M9sTIwidYDRKjkMfz6D5aqpm8/9tm/2sGIQaoZuEagZ79Q4NToTRbdel6XLrC3MDR6JogonX/yrtB1Qm9raUJao/BhnOcxekj1YQXN1K8I91kMVtSAY4CwkWSXb/f7A1pimR2l1SVJAdLaRsNBUas6NAcBf7q3fci+iOBtJZo5,iv:5BLELedQg4Tw3v7zvTMetEbRTywQIdaAej8G7ztAoFA=,tag:JoI9jD6sp1nDnT8fZLbOlg==,type:str]
  OIDC_CONFIG_DICT: ENC[AES256_GCM,data:y6yvph0EOGv1b/zlWK4TFYUrLoaQS7IOvf7aJ/Qn1GPD5VjPKf6kActDR4XQERN7iWdgHkzLIJp5Tz9HEXhUzMtGYhvQl1CT8a7l8UkgZ29jP7A2PxEv6JNBaygAQyZ9NOt+8JLnBwM3KhGEaeG2OEbBMuEivKu3paCrKrs2bSAWQCZf5zVSQrASRSNRvNkTtYFQDdklOtbvgRltcU8Emy5v1six3hMKqWD7LQBLeAtc8R7V82GTsAwzvp1hgaAtcuEQ/0xKHje0N3DNsxf2QRSIDVLjFuaqXy9ytYmcjpHheA==,iv:xQThPj5UbhOyVl/peUquRS1Q8XvZgeJmHXSpemp+qbg=,tag:ZF7mDr1ffzFktTzUX43Nbg==,type:str]
sops:
  lastmodified: "2025-11-11T13:48:59Z"
  mac: ENC[AES256_GCM,data:f6Wi9qZ0Pr1uabxV4juLUARJ8K0MfOJoXorM5AKO92RWjj99yVHLKTmIDy+JIFHy+soCe+VfnAvF5mi3frGi/ZLzuFv4srxP1zYmlBoM2eWmUaTrc6V73rEhMCw3xvq9TJxVFs4/hpq9ZBWZ40ozdRpnxkwt/GEyKWt5jtmjNPM=,iv:APZrUMn68lFz01VMVbbOqeoF9ZfmyZUB1BYSNv470xA=,tag:P9FA5CK309jAm0OFexiOSA==,type:str]
  pgp:
    - created_at: "2025-08-12T14:08:37Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAjJO1d0laKZOvpdXRf8OGGK8ZI5XEPfUQaZ916rCuQdv1
        aOuonuJSEMoUQyJ1L3mogR5R3GijZeTz4PtILSPhmGoBtd4SDhoXE1xdk00dQQ2c
        YVRBegnBSi2+ofaCU2oZvwiM5Ut5TcmsB3DewNuFsa8GMh/OSDyru/dbPm7A/WQc
        /67/OunSn939yvaLvN7U7MGyJdlZnAdtf9+vhifFJWOfvbmcwV6cpkg2bSczSdwc
        bGn3S2O90wv4AgSACyf1QgfmqenRhQoQy3GrFC8Uco5F46QPRz/lOhbdm7aWw1IB
        dIEF7RIZ2Efyswl8oQXxRkOlTuFV3sCbxRTD+POeW4OmyWO/326JAnmRUzU35bQL
        ISp+Db7X5dpJ9Gn9E47ze/dYqnltfHcjGZzFV836/OgvLA4Tu9uYxNplXnA0MGFu
        25X+deN0HxRTil2YyWsvPHjwWPwlOV9ab7119zKwAatTQkIPt3xBpXjiOmDCO5Xd
        BAJWxgJY66ns9kXqbP73jP6NbKXLSM8Uju12+NIkogD3F6gtOSDnw34soCVT5/p8
        dPqXPXHIdaDT6ASSZPoHW8IGIxQMwqNZjZcW8czHvzSn8k7sjwO5kDewQmb+xFBG
        WTVU45ZmYO4cnuj39IcFTl9Eb7bvZ32DWb250KVqAaUTEWarO3tdVxwTQFA2nSLS
        XAGMPRcOnhlNRI2ZmfFtl7irro3fC56SHgav1/ApcSMb+UpL7QbalTcKbwEkOZcl
        mmPYFP2YjdCHqAGCmLoF4WljYS6cGTFFYqqkaiW8VkygxEV2K/0W6DO2Gvxa
        =uMlZ
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
