virtiofs_mounts:
  /mnt/tank/media: tank-media

extra_args: >-
  {{ '--flannel-iface=' + flannel_iface if calico_iface is not defined and cilium_iface is not defined else '' }}
  --node-ip={{ k3s_node_ip }}
  --node-label role=media
