# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname postgresus
  namespace: flux-system
spec:
  targetNamespace: database
  interval: 1h
  retryInterval: 1m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/prod/database/postgresus/app
  prune: true
  wait: true
  postBuild:
    substitute:
      APP: *appname
