apiVersion: v1
kind: Secret
metadata:
  name: rxresume-secret
stringData:
  AUTH_SECRET: ENC[AES256_GCM,data:j+TuvenB1pUzAjGE/2TRTW0jmvtw8w/dK8mSuRvr6eDgNXCKkMenbdJ17oXAZnlgVWtoaAa1qysuStG/55gfHA==,iv:ytkTrROCDiDJdHayRvn5yg7VghFPbLcODGVAoKLMeOw=,tag:wEZGxVcvZmai9YDCivbZ4Q==,type:str]
  OAUTH_AUTHORIZATION_URL: ENC[AES256_GCM,data:RwtGXe+YYJdoxeunWLYlGMSjErwIYtXbhXLYvAT5/9XOzV0Tdst5eIEpUyTVW2AY7RGIt1jXS8nwaOQY83LYZXe41zSAJRDGV40ICUoqlPfD,iv:b3KGfKCM7r6gRdgTPxEl072Bv690LAHGwJFSJ8rbpXo=,tag:aVj5mkxpqJBOI0b9pbiAmA==,type:str]
  OAUTH_CALLBACK_URL: ENC[AES256_GCM,data:tRvo8lvPN55ZBvqvYhoPIoVkAJXvP1L45S8J7xp4+oRqfsR8SfcC2O9x5UHAC+GBinkdNGnpq66jlw==,iv:ojS+zID58VViuqihr7FB7wpxHC5O2/B91BRWqTWd5lo=,tag:lhAXwVNgKPgTsPlQ9R9Eyw==,type:str]
  OAUTH_CLIENT_ID: ENC[AES256_GCM,data:3z8eoqDvU6A=,iv:e1IguVZPRYmXUbiSAbDvKU+0na13LkurzJrzohMcAMg=,tag:yz5yMM8da/LIV2EkRYRvWQ==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:JSCc2pVCZh1KNdWIl1lOm/gscCzNrXixlsW5T/63pyM=,iv:MW9FRTDRlrOi7xyvVZ605dwy3M3g4n6xDees0PE3hKc=,tag:sP6Edl1/iZrtVWIyym0bQw==,type:str]
  OAUTH_DISCOVERY_URL: ENC[AES256_GCM,data:28GcG8mu4zX15Qd/g9BzdjMJ55c8P7nwwKbfAFWoX/M8C/9hpIWoetDYEPvjr60C/9jS/SKfs2nQK3Do1z+CAV4etRX9qq5GA846N1/4uK5UkD1fhg==,iv:x2HYIq+SKRBCmh05GJ+MIJOipnJSjA5fe3e+eONeVFE=,tag:8bz+WhNXMHVPI259sf2TKg==,type:str]
sops:
  lastmodified: "2026-01-20T13:13:13Z"
  mac: ENC[AES256_GCM,data:b/R08e59VkMgwqXdLYszvs5BuXDctg6657L+/GpyIpUJQGU8wmcTc/a+Rj/905TRTuIS2PLrhzHeGrAHSVQykJHcKhgCJfpZGnQpYP3DZ5WIkoaCwDq8FlD6LbBnzjw5O7Mn54uixoab8RAflI9XSb/6iJcuf3tXVaJiW9trL7M=,iv:HevyzFjRVobwAeee8gp07D2coRnHG0uDTmGrWneLs6k=,tag:BITsWw87EeMhS/1HFPqkag==,type:str]
  pgp:
    - created_at: "2025-08-12T14:08:37Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAjJO1d0laKZOvpdXRf8OGGK8ZI5XEPfUQaZ916rCuQdv1
        aOuonuJSEMoUQyJ1L3mogR5R3GijZeTz4PtILSPhmGoBtd4SDhoXE1xdk00dQQ2c
        YVRBegnBSi2+ofaCU2oZvwiM5Ut5TcmsB3DewNuFsa8GMh/OSDyru/dbPm7A/WQc
        /67/OunSn939yvaLvN7U7MGyJdlZnAdtf9+vhifFJWOfvbmcwV6cpkg2bSczSdwc
        bGn3S2O90wv4AgSACyf1QgfmqenRhQoQy3GrFC8Uco5F46QPRz/lOhbdm7aWw1IB
        dIEF7RIZ2Efyswl8oQXxRkOlTuFV3sCbxRTD+POeW4OmyWO/326JAnmRUzU35bQL
        ISp+Db7X5dpJ9Gn9E47ze/dYqnltfHcjGZzFV836/OgvLA4Tu9uYxNplXnA0MGFu
        25X+deN0HxRTil2YyWsvPHjwWPwlOV9ab7119zKwAatTQkIPt3xBpXjiOmDCO5Xd
        BAJWxgJY66ns9kXqbP73jP6NbKXLSM8Uju12+NIkogD3F6gtOSDnw34soCVT5/p8
        dPqXPXHIdaDT6ASSZPoHW8IGIxQMwqNZjZcW8czHvzSn8k7sjwO5kDewQmb+xFBG
        WTVU45ZmYO4cnuj39IcFTl9Eb7bvZ32DWb250KVqAaUTEWarO3tdVxwTQFA2nSLS
        XAGMPRcOnhlNRI2ZmfFtl7irro3fC56SHgav1/ApcSMb+UpL7QbalTcKbwEkOZcl
        mmPYFP2YjdCHqAGCmLoF4WljYS6cGTFFYqqkaiW8VkygxEV2K/0W6DO2Gvxa
        =uMlZ
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: gotenberg-secret
stringData:
  GOTENBERG_API_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:/ieBcEIz9PE+w82+FKJEYwwDg0EFRUhf0d6JfvoeCcIW7Q==,iv:iOfWo/odt+B9EgBKHLejZoBM/LfFbSYHtm6/cHh1CIc=,tag:5Pln3Ucz0tS6JATx3BATIw==,type:str]
  GOTENBERG_API_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:JtUbfy/SUymPoO3LJrBjvl4MJmP5BPozaRkxhfxEv79AGUfXygnr9K0/T155XFVK,iv:C9NQpIQ4swin3BBTUjFQ8lrX8gyU6me3BHK2wqo7SuU=,tag:1ap4uhPun4XA79zxp+SrkQ==,type:str]
sops:
  lastmodified: "2026-01-20T13:13:13Z"
  mac: ENC[AES256_GCM,data:b/R08e59VkMgwqXdLYszvs5BuXDctg6657L+/GpyIpUJQGU8wmcTc/a+Rj/905TRTuIS2PLrhzHeGrAHSVQykJHcKhgCJfpZGnQpYP3DZ5WIkoaCwDq8FlD6LbBnzjw5O7Mn54uixoab8RAflI9XSb/6iJcuf3tXVaJiW9trL7M=,iv:HevyzFjRVobwAeee8gp07D2coRnHG0uDTmGrWneLs6k=,tag:BITsWw87EeMhS/1HFPqkag==,type:str]
  pgp:
    - created_at: "2025-08-12T14:08:37Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAjJO1d0laKZOvpdXRf8OGGK8ZI5XEPfUQaZ916rCuQdv1
        aOuonuJSEMoUQyJ1L3mogR5R3GijZeTz4PtILSPhmGoBtd4SDhoXE1xdk00dQQ2c
        YVRBegnBSi2+ofaCU2oZvwiM5Ut5TcmsB3DewNuFsa8GMh/OSDyru/dbPm7A/WQc
        /67/OunSn939yvaLvN7U7MGyJdlZnAdtf9+vhifFJWOfvbmcwV6cpkg2bSczSdwc
        bGn3S2O90wv4AgSACyf1QgfmqenRhQoQy3GrFC8Uco5F46QPRz/lOhbdm7aWw1IB
        dIEF7RIZ2Efyswl8oQXxRkOlTuFV3sCbxRTD+POeW4OmyWO/326JAnmRUzU35bQL
        ISp+Db7X5dpJ9Gn9E47ze/dYqnltfHcjGZzFV836/OgvLA4Tu9uYxNplXnA0MGFu
        25X+deN0HxRTil2YyWsvPHjwWPwlOV9ab7119zKwAatTQkIPt3xBpXjiOmDCO5Xd
        BAJWxgJY66ns9kXqbP73jP6NbKXLSM8Uju12+NIkogD3F6gtOSDnw34soCVT5/p8
        dPqXPXHIdaDT6ASSZPoHW8IGIxQMwqNZjZcW8czHvzSn8k7sjwO5kDewQmb+xFBG
        WTVU45ZmYO4cnuj39IcFTl9Eb7bvZ32DWb250KVqAaUTEWarO3tdVxwTQFA2nSLS
        XAGMPRcOnhlNRI2ZmfFtl7irro3fC56SHgav1/ApcSMb+UpL7QbalTcKbwEkOZcl
        mmPYFP2YjdCHqAGCmLoF4WljYS6cGTFFYqqkaiW8VkygxEV2K/0W6DO2Gvxa
        =uMlZ
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
