apiVersion: v1
kind: Secret
metadata:
  name: tinyauth-secret
stringData:
  #ENC[AES256_GCM,data:ttqDaQ==,iv:jGmpE1Vmtn067m+dC5wkeG0UKE1UYstbCkqUB35lSAo=,tag:F/sdFi8IWzcekljhB84sqA==,type:comment]
  SECRET: ENC[AES256_GCM,data:LETbQh+NS4a6LkNMHB0pmrNt7T9kog==,iv:N3s28GEvxXlZm/PzTI5GMrjeKS/4X+ASZafEAp+L91I=,tag:2hCipEIiHEvWd3pdW05ShQ==,type:str]
  #ENC[AES256_GCM,data:i9ETeXc=,iv:/vqTx3XssmA2OMNYrBT10xywzUuBolxMCchO0oz1MqY=,tag:IadygKZnmRd+HysXj5lRCw==,type:comment]
  PROVIDERS_POCKETID_CLIENT_ID: ENC[AES256_GCM,data:Qx1YJmuScQ8=,iv:gK2Esiy80ReQpq/WroMFsU8Wd7QfpBvD5IxYqjb0t+Q=,tag:drdatUTnd0TtaKVL24wA+A==,type:str]
  PROVIDERS_POCKETID_CLIENT_SECRET: ENC[AES256_GCM,data:4aN/d/PwdOAQaATAabM34u2ey3d3WbkwnhybqVAj7uA=,iv:Zl6uZDAYOMZaub04+DrBYpgme7dWf6Pi8OhJIw9ROV4=,tag:V7BBJXBPrdm+0Wel5MxyDg==,type:str]
sops:
  lastmodified: "2025-12-21T11:56:56Z"
  mac: ENC[AES256_GCM,data:2m8QykoGUIPWNixKWPQiVxtFQQNF2IoWkce2/LyA7QH66weYcnoK0s0HyIhsyFeZqAQwz3KBEEEEGpMpRfbrr3EUdRph+66lsL1Bd9ZgDEHlDZii5DSEsU2BQ416S5Bmf2gWGm1H5gD/F1BNeTh4h2UjwxNlNkVFWSp6+Ni2fj0=,iv:jUjxkglVhMUuAcgkXGLsyDUgjYpE3x1FwaqUsY6BLf8=,tag:5RA/07bcpjOwjweW18Zl5Q==,type:str]
  pgp:
    - created_at: "2025-12-21T11:55:06Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLAQ//celMF1LAFpApbLPuJHtRQc9/YQQx4ph7vU8CavmsGasx
        pyMQaxXDlXnpvpcYn2eP/ZGYmSIlMnIDsVSuyewGXP2TqIexbw1KKuomBxAAQH1b
        jeZmRrJmhmACeeU+24jUEmDolVq3KObU1UPzr5SK4QRTmLUqL/ORXt1JxJIcE/37
        szFLmGlo6ugW+DbQgc5IqX8uP8l4tVmz+7qmkuyKREs1WndWWm2b6l356xuaTOS6
        5EuEKr4KNEqpZVlIvqskgDxWEyNN02dju/tr8vRIHscSdFx9yDgwGzo/0nXmEON7
        aaDoXoDiPdE7MS9ziu0Q8YOmvXLEl6BBVqCFUwNcWlwXaNY+/xzyFLF6ntpubSsy
        x5pye8/4xblugLPdkDDwHO5ohzNATd+XdWcgsn8FfwVqPq6LUouVxRgu+oBSwSoB
        35hKBNhXjGTjl8Fgcz7+Ef6qFRrK6uHW6ulzDYKb0NeNIxgyNWvknk7lvWM92Y5W
        utEujo6YNJXCyI1DNLaEjBm6yCuUrnLLNrZNfmRk38BzLxOjyO6BctK/9hUqbFxZ
        PQu3FHD9ImAp5SakYnAqrcJ06wAeZLtQ9/5an7n5dq4tYRVR1hK1pfA3fLMtMRNl
        qAm3vv2RYgl2sdZZaEasa5q5xlxAZk929FQzqKzbxTFDAK3kaUXGcUeJrPyESCjS
        XgFkKNsE4d1L8ymfTS/bC7y5pkuWYQY/OefPyWrNwrSNBFBJxg1tRpmHvT1bTJnq
        rjepsT/ki/pbdpTY5dLF1jpTPLC8d+uYn9WKDLeaIVWm+f06F0v+wdQcqvb46lU=
        =XHxE
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
