apiVersion: v1
kind: Secret
metadata:
  name: tinyauth-secret
stringData:
  #ENC[AES256_GCM,data:ttqDaQ==,iv:jGmpE1Vmtn067m+dC5wkeG0UKE1UYstbCkqUB35lSAo=,tag:F/sdFi8IWzcekljhB84sqA==,type:comment]
  #ENC[AES256_GCM,data:5prSflvk9L2z23e1wVIwmpBztZInTHyjmA5giCaUbmrX,iv:v+t1WNsT8S/9WuCYWqJlkqOXLtby3BNR43po56kB+wg=,tag:KSlagNIfVGj6AEcDR2SupQ==,type:comment]
  #ENC[AES256_GCM,data:i9ETeXc=,iv:/vqTx3XssmA2OMNYrBT10xywzUuBolxMCchO0oz1MqY=,tag:IadygKZnmRd+HysXj5lRCw==,type:comment]
  PROVIDERS_KEYCLOAK_CLIENT_ID: ENC[AES256_GCM,data:L0Acs2tS7mA=,iv:ueJfY3bwFX4xNENocLWApvKyJ7dipzdtn3/MB53NlNY=,tag:7z1uKBpgY4T2y1K1z02zdQ==,type:str]
  PROVIDERS_KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:riLeSYLFmP75zBThRafz0dyJUk1eNd3391gnqNgBlTc=,iv:0ircXUL/PQvNhsCrB0iVrkUB+ed0SsJnAtte9wXS+tc=,tag:5sSBlfza9WCRnTx7wtbCrQ==,type:str]
sops:
  lastmodified: "2025-12-21T12:32:01Z"
  mac: ENC[AES256_GCM,data:42SQZ6YDEygpBOtrGifFQscNro9U/K5HvJF+ngqZnF/m2SZa7f/l0gKcvPwIbYXKA5Np4T2ldoCT94dA1KHuTC715mfuRZkjg2/cQs1DhVOPIxlVRtrMKP5ISwyTT8a1WcJHZd6Ht7MsTTTJKlJZbx/O3ApNnyvSIJvlEZF+LLQ=,iv:Mn3VNifbYxvn2gFfXXtVPKp1uyHteW92F0lgdRm+UZ8=,tag:26ztWhGETMxmskPx7HZyIQ==,type:str]
  pgp:
    - created_at: "2025-12-21T11:55:06Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLAQ//celMF1LAFpApbLPuJHtRQc9/YQQx4ph7vU8CavmsGasx
        pyMQaxXDlXnpvpcYn2eP/ZGYmSIlMnIDsVSuyewGXP2TqIexbw1KKuomBxAAQH1b
        jeZmRrJmhmACeeU+24jUEmDolVq3KObU1UPzr5SK4QRTmLUqL/ORXt1JxJIcE/37
        szFLmGlo6ugW+DbQgc5IqX8uP8l4tVmz+7qmkuyKREs1WndWWm2b6l356xuaTOS6
        5EuEKr4KNEqpZVlIvqskgDxWEyNN02dju/tr8vRIHscSdFx9yDgwGzo/0nXmEON7
        aaDoXoDiPdE7MS9ziu0Q8YOmvXLEl6BBVqCFUwNcWlwXaNY+/xzyFLF6ntpubSsy
        x5pye8/4xblugLPdkDDwHO5ohzNATd+XdWcgsn8FfwVqPq6LUouVxRgu+oBSwSoB
        35hKBNhXjGTjl8Fgcz7+Ef6qFRrK6uHW6ulzDYKb0NeNIxgyNWvknk7lvWM92Y5W
        utEujo6YNJXCyI1DNLaEjBm6yCuUrnLLNrZNfmRk38BzLxOjyO6BctK/9hUqbFxZ
        PQu3FHD9ImAp5SakYnAqrcJ06wAeZLtQ9/5an7n5dq4tYRVR1hK1pfA3fLMtMRNl
        qAm3vv2RYgl2sdZZaEasa5q5xlxAZk929FQzqKzbxTFDAK3kaUXGcUeJrPyESCjS
        XgFkKNsE4d1L8ymfTS/bC7y5pkuWYQY/OefPyWrNwrSNBFBJxg1tRpmHvT1bTJnq
        rjepsT/ki/pbdpTY5dLF1jpTPLC8d+uYn9WKDLeaIVWm+f06F0v+wdQcqvb46lU=
        =XHxE
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
