apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-nfs-${APP}
spec:
  storageClassName: backup-nfs-${APP}
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /tank/backups/apps/${APP}
    server: 192.168.0.51
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-nfs-${APP}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: backup-nfs-${APP}
  resources:
    requests:
      storage: 1Mi
