apiVersion: v1
kind: Secret
metadata:
  name: vikunja-secret
stringData:
  VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:d2ZQ9xg7GSQqG5V6a3C/BVHrsSdcgBZCF7Gqrl3ywu9w9Wmes3i2vIZLRiZEFDlMglLneVtqgNtX7qjyWhE8NPGYVe8jj8a3U6P4kwENOuYWdK/pJn49FlBelYziNOqRYuNdxgupAfuSB/QhcjIw7hzGJZJYIXqorGu+/RCf0iI=,iv:lpqX9YUCAmu8AU7iQiAbzyXq7JzZZoo2PzwyoEiSEYc=,tag:EaWxXSvhM8NBwfCVhEV1nQ==,type:str]
  VIKUNJA_MAILER_FROMEMAIL: ENC[AES256_GCM,data:L+kEISXKgKb1PGHGMww/Tkrt,iv:a45U3JWTZZgw0llNMUvoBkOYpG5I6zxGNXsPUhy0X4U=,tag:ru0o45zcNRlfMQt8xrHumw==,type:str]
  VIKUNJA_MAILER_USERNAME: ENC[AES256_GCM,data:ljO35sa1Krx8P7XgyjqIhBiC,iv:rMwLk7OlawAL/1NB2yt7APXMp2B/l5ujpeVoz3nQmy4=,tag:aQIgRpibTRPBla0J7eFz4g==,type:str]
  VIKUNJA_MAILER_PASSWORD: ENC[AES256_GCM,data:nrxe2kYSxy/rLYrEtV5shA==,iv:PPHEl03/hZYV1a3JjnfKKk6Z+mdxht5kjsg+pCIzUK0=,tag:IHpCuL57CHNpUsCynU67dA==,type:str]
  config.yaml: ENC[AES256_GCM,data:H2EzeMwWheWuIwTUK6zFsZKoDbyj/h2Q7XwcgoCkR7FmDKpKppqf2CyNK8HEZEqPGZPnNFSOfkQlwN+S/hDhFYJ1bO1tLHCPsOcyXEgOWLs+jS9SrgRI5WeJHJg6dlh9swOZjTonXU8AmoCyxxXlaWQQB+kwNa+sMRoySvKIKCOSnpcrhlu4XpvHodSOKulqxFziPvB2o4Ifv+oIWL9XFVVNLZk/P78byFG4bDdlTCt0MQNqO9rBCQhkCFfyxImGSGyqDUh2e1ZcgTs3tGIaHV5gQARCrCkHlTsAmbfCjSyeVMM4hvowMjPHP2txld2iSD5B4RpVoyQ6KDiMAv5tYYq879Kqt+iS4+QMDFDWOb8MpOXYU7ekNmjEVEe+Zwc0XMWV+BPU9S/QYnp3uahqUPd5e/mx5NCEFhFDEGvqEsqmPmnBI7gpKynzESvbTh73vncxURd/pEyh5tvnP7liqgg=,iv:4ajGpEWS5+rBVuyQyqnYU6f/QpJ/6PdklVGvk+Nc/hc=,tag:0SXxCtAOvJ2rky9GKmCe3A==,type:str]
sops:
  lastmodified: "2026-01-03T14:18:20Z"
  mac: ENC[AES256_GCM,data:i5bUlI2Q41GkvceZ/qsUDgk+esQFkNBXVmvobQG1bVxb61OkZv3IoqTIPUdymbHeD3wDXfpgDI59VPy5p3MxkO+o1cd4fQz1DOJu5hDWGaO0eWrCOWwlBJFkCFk/5dO+Qu2dmRfaeCGhmwwFcfwU9B8R9flOiyktCGqPpHZa5YA=,iv:CHB21/f8OPXChNVZaqGh5TS8U0bfB6mgE2kdno7nfPg=,tag:XFj3AoJkP8GUd9SyEbbCPg==,type:str]
  pgp:
    - created_at: "2025-12-30T21:41:20Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAj1mQBzs75ytiVmbeCndz2+Fgt1SmamO4kTQcQm55xlNk
        vuGUVFFjoa+KESboYxqGxEmyrjMrjN2RDxciBeJCPs3xgAfksoRN34VNeeR76hL4
        HZKi4uSMepgAqHTwFFyCaMo8jliHnM7bQsljf3P0mius0uJgmPaB5g7cdd7Sn9U0
        RxquvZx+V8tP1hdaQe+teaiwaNutChqwrsLk7k+qKADCbdtBvmXEGuyASS158ekk
        2v/5PhhqLmCS6IU+Jo1OH2rBbtKUpeoDIy9i22kwWoSRkHUmlD9z52/AvO/Zzu/9
        ZU8yVNgN06kx7jMpr1ILhMeCeV3b4eAJqkixjIMxXfaKyhjUXF5HsQ8KMfp9sf9n
        +0RZqu7uTb1Ckx3L4tRy2pQHyA3v9dBijkKBbq2Kl/yfxp1FWOuPhG/ELjTjMXZ8
        jLy2kW2L96SkaAZjQsMy5/nr12JrR2PetOnhzgbH91nc73XVpMMdGsB2+L8lTbYi
        lN/bB7zNxHVzeOXjmfaNHbxVoFIJZ6QN+34pHIxn0Deoc/qx/KW6/gCRKPqwfhXw
        JxtkWjoUV85bb8Idktv1H2ManU1DcDPZPMRj47MixOCU2tR9qpLMdbhGm8XVyWIz
        LxeCcaCgKOUn4NnjaMnP6awacx+lXSYyj68dRoI1ixLAc4Dz6NGt7B3JKM/DZTbS
        XgEohkNS4bBnlROIzUl48hBSv3kp4QAjPEmtDLB3hva3M8DCkeg5kCecK2sfBrFH
        ZGhqwaW9atOE6utTcEynFYwnkfTZ5SS5Y9w0Bq7XElQaZ3NNODtMeTzCj9q+Hiw=
        =y5kg
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
