apiVersion: v1
kind: Secret
metadata:
  name: vikunja-secret
stringData:
  VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:d2ZQ9xg7GSQqG5V6a3C/BVHrsSdcgBZCF7Gqrl3ywu9w9Wmes3i2vIZLRiZEFDlMglLneVtqgNtX7qjyWhE8NPGYVe8jj8a3U6P4kwENOuYWdK/pJn49FlBelYziNOqRYuNdxgupAfuSB/QhcjIw7hzGJZJYIXqorGu+/RCf0iI=,iv:lpqX9YUCAmu8AU7iQiAbzyXq7JzZZoo2PzwyoEiSEYc=,tag:EaWxXSvhM8NBwfCVhEV1nQ==,type:str]
  VIKUNJA_MAILER_USERNAME: ENC[AES256_GCM,data:ljO35sa1Krx8P7XgyjqIhBiC,iv:rMwLk7OlawAL/1NB2yt7APXMp2B/l5ujpeVoz3nQmy4=,tag:aQIgRpibTRPBla0J7eFz4g==,type:str]
  VIKUNJA_MAILER_PASSWORD: ENC[AES256_GCM,data:nrxe2kYSxy/rLYrEtV5shA==,iv:PPHEl03/hZYV1a3JjnfKKk6Z+mdxht5kjsg+pCIzUK0=,tag:IHpCuL57CHNpUsCynU67dA==,type:str]
  config.yaml: ENC[AES256_GCM,data:T5gBx/60k1nRZz2rU+peDaF9Wx1EgF2JmlpQV60PuwY6NcZPLj2FQnYAtetzl8U3lS1D1HPhwGJxHl+7bneJA/F6iDuROzqLvc6F6DJqEpTw13zzP2gmhBcp++s2UzuzxfFMM5OSlugGuFV8YPc3K2YqfD6P7+KQRw14q6XdQ6K/4L7xBa2F9aM+PVHDe/XCIYHPv2q/0AK8HUK0UGRvCDEFFHXsPhpXkL3WosXPIZQ7nXhkAyNeCQhYuRcQjMITaJ+83gBwf4c9J+rzFmS+8C1Qo4gIKTWJKvrVyWWPnmSzmZySJSwRSBk871yrHfREDaJtUDT0ctQNnq8CKtvJ8FqRdryAJcOBvk+soKy2D3zOj4bxwiNs8eYDU6Mw86AZyJnrdtWKp0DlYd6cWlkZxDsUWxD1OQaKeo6+dIB7QiVatcnC5MyUVfztANdfldM3TkrsoIN52nsEgVg=,iv:iKdSHhcvPtUUDku2QNMcj3J3xQ5mK3AoElLlchLMu3k=,tag:2B4tbW/HBuyDIy2Zq+tnQg==,type:str]
sops:
  lastmodified: "2026-01-03T12:12:28Z"
  mac: ENC[AES256_GCM,data:mvm8elhHetVDD2zV5nsSiSNAt66uHCVzClOswN4PojRUF4sI+maNeP3fwQyQpgagfaThV0k7G3OiixYH/cqy2LNQ9/7lRhtQeKniwBsAHWIzDTvu5VU+SRKfdDFoUNXSxtHNu2VyuyMzJv8AxtCtSw4pBWhPvgJHM8Uc5RjCfkM=,iv:LpYt8jCELR8L30Xr8ofXIgEDVgDtBcfKleHE0vh/lmY=,tag:RxemyQUiyv5Ejw/4OCyhmQ==,type:str]
  pgp:
    - created_at: "2025-12-30T21:41:20Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAj1mQBzs75ytiVmbeCndz2+Fgt1SmamO4kTQcQm55xlNk
        vuGUVFFjoa+KESboYxqGxEmyrjMrjN2RDxciBeJCPs3xgAfksoRN34VNeeR76hL4
        HZKi4uSMepgAqHTwFFyCaMo8jliHnM7bQsljf3P0mius0uJgmPaB5g7cdd7Sn9U0
        RxquvZx+V8tP1hdaQe+teaiwaNutChqwrsLk7k+qKADCbdtBvmXEGuyASS158ekk
        2v/5PhhqLmCS6IU+Jo1OH2rBbtKUpeoDIy9i22kwWoSRkHUmlD9z52/AvO/Zzu/9
        ZU8yVNgN06kx7jMpr1ILhMeCeV3b4eAJqkixjIMxXfaKyhjUXF5HsQ8KMfp9sf9n
        +0RZqu7uTb1Ckx3L4tRy2pQHyA3v9dBijkKBbq2Kl/yfxp1FWOuPhG/ELjTjMXZ8
        jLy2kW2L96SkaAZjQsMy5/nr12JrR2PetOnhzgbH91nc73XVpMMdGsB2+L8lTbYi
        lN/bB7zNxHVzeOXjmfaNHbxVoFIJZ6QN+34pHIxn0Deoc/qx/KW6/gCRKPqwfhXw
        JxtkWjoUV85bb8Idktv1H2ManU1DcDPZPMRj47MixOCU2tR9qpLMdbhGm8XVyWIz
        LxeCcaCgKOUn4NnjaMnP6awacx+lXSYyj68dRoI1ixLAc4Dz6NGt7B3JKM/DZTbS
        XgEohkNS4bBnlROIzUl48hBSv3kp4QAjPEmtDLB3hva3M8DCkeg5kCecK2sfBrFH
        ZGhqwaW9atOE6utTcEynFYwnkfTZ5SS5Y9w0Bq7XElQaZ3NNODtMeTzCj9q+Hiw=
        =y5kg
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
