apiVersion: v1
kind: Secret
metadata:
  name: donetick-secret
stringData:
  config.yaml: ENC[AES256_GCM,data:rq+HSGO1hMP83q/6jB3q1HKWYdJjy//g3wIsUXwJ+JiZqx4J+w06xz+n3kStJezyxF4DIKMyamNkzXPUQC1EWvA/Y2hwyHjyDIztEDMmNYSv2VyJfjWYyh6RWi1cIku+14ILpG4owOUfv2lbYNhn6+7ByF0fW5mWOS05VCIsB5JVB4Sv++vvHnbutgc1laFTRIW95LUp3vYJU1AiBnGw0zMQp5/SMqOYPshkCgg36RQPoTl/KXmknNP0mh8EdkdDI9U19M2F57askphIZvS7Af+9fHsbiFLrjbwDZNBMth26cgODzuH1fl4WCr7dP+AlNiuLGcZvMsK9EaIZM6bU6TGR2c1G1Gg9s/bbRulL3xahA/gD9rxUZde/wqTdTrphCBRtdNjmuxEFmrh1sOBmI8abV6RoUHSvBKDreYmGdBjdKGbvSEqYXnkqEnH2P20v/kKN0if0US/Zi6g3TDN630YCFfCOG42oJyEmYgX0BvQExUB1tLiN10tJcieb8uLKK4Fhnw8hQjhN2/WCcH4Yk0bLcJkcE7UWaSLaV/cxpd3Q2mlg32DasNmu4Xd8eNFXf2vzDRzqzPctZFRKmwqeTiLAQRLbMEMO+W08ooYfY+/kvJc/Ji428AqjX1wZds/2x+KXJov4rVqYXE1gag6VHVfGpv6/dtuU+/s9ENzgXxSKm75TqczWAFVtbRf2PvICDyEeFeljU5dB6y/2CksuPZIZ5SmBLjPD46dhidygRIeCHTP47LTTWWPdB4EtCs4GBLmxKKzvD7pAaLmqDd5k56eoUf0IE3V1v4wi9fJTuCjaNbd36Dh9xUQcdxaYrGUH6OAXpkjlLFTone+TvyGWD8D7eYWob5lkw5/JiQu85UHW/wWC37PkQtWyFQgoSp7Dn8eqjEq4q7SUJhtUlpttDcT+uYbmnuwbZA8y+H13s12Mt4auNKlQ3zJTuUKcJpQVg3nn3Y1RYgMvmMuFSltTxewieZKePB3GlnfDCPsXgvSk5XtmMdqJbiYhrgyyI4D6GLcd6rWcu+0ohjbeWRhg4Rx2H0UXUU34aLX0g3gR+DfB3FEfyW3IIhUkFi46+ZRmT62dNp4Cfw9IEnQYvadAymeRo2pmgHQGruHFpHDTCGSg76A0aUtddsOg3mYdFONAyX/fFHockgCsEWOZSQGcJe1DaBFrWQBiM5g/jepvBfO8/Vd5/wyxFrnAU/RXaI3AxZLRsc/ipztSjuNEPxkQJgugOFAxWlG4t2UBoC7a3dXSUHzOEJG9DVVRKenW5D9QgaYmyIyItNGgOOJjTi4o/jZy9LZRhteYY+L+dMz/j0vjtFL2ddsZJZ+ycU5p/MeQpzkZJayix2bSsU40CmTyCANbqw174RjBePbYTnSKHlfwvfSikoT2jf/umGau8aAkzvgB3/6IOfFKRpNhK97lLe6KcmwYMd7F8YgDpdGO+wdKtzxRyQ+enbxjH4ftL+5K0KOqJzB6z7BDENEc7lX5cOD22vuTCXfOPFkc4hHijHLJt6geF6UF3NS3Z7TDe+Uwxz3u2fmQD2jGRylhV0LPmygj3xPHR2HsYZVeTiy1IVBHzMTL5JF9a2cz9d7uqYJBFLsMP5Jcgg8XOA+C0Aze65W8cV/UK4Jr9z18Poxp4+m5aZ8pRPU6C4fZ/Ih1b/FEKqX0YngCJNyVGnr2iLbifOooTWQ4M4Au8asw848Ybs520s7OgY69bU8V2FshVra9RsUP/1oLM7yWDgkETMh52HyP+E73T7gnW7/TcpjlQA5mJREL3tVgetwRT/Kl7FXGWdikztqE9y7ULGvUKIa+1QgFsLyjc2rk8x9Hdrby9xctVDPj8XuIVjsXuArhJO4lMJ98WAjo+3LH3bLe8yDf/UbwofBFzH0wpE85V1YSsOeGqOVRXlYdthaFz5HSKaMZS2SUUl3HmwoL,iv:SSIVw/K3ZwVPK7qUN4h6TYALkyiVi2zSb4Tc0H9opcI=,tag:/m1xOFOT8jQIkax5mcdr+g==,type:str]
sops:
  lastmodified: "2025-12-30T21:41:20Z"
  mac: ENC[AES256_GCM,data:bdLGs2oWf2w/buMTm+UeIq8aiX6c0YfQ/NGlxJpHMvG5m21TPv0TX/m22F1kwGXifWbkALu7NWgDLYvN72mER4jbY/yIry45Rd41lVYeuAg1mBz1P3P4ehWoNfWxY1yycaEf5hC6ZF7e1dytsQ/46hkb76nBQZ5YDCP5R1LvUh0=,iv:r4Txw7EGTRahXyVWnYJ6Bst2SRMitZBantozetpfVyQ=,tag:ujBud/GsCzc7V+mO1aWk5w==,type:str]
  pgp:
    - created_at: "2025-12-30T21:41:20Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAj1mQBzs75ytiVmbeCndz2+Fgt1SmamO4kTQcQm55xlNk
        vuGUVFFjoa+KESboYxqGxEmyrjMrjN2RDxciBeJCPs3xgAfksoRN34VNeeR76hL4
        HZKi4uSMepgAqHTwFFyCaMo8jliHnM7bQsljf3P0mius0uJgmPaB5g7cdd7Sn9U0
        RxquvZx+V8tP1hdaQe+teaiwaNutChqwrsLk7k+qKADCbdtBvmXEGuyASS158ekk
        2v/5PhhqLmCS6IU+Jo1OH2rBbtKUpeoDIy9i22kwWoSRkHUmlD9z52/AvO/Zzu/9
        ZU8yVNgN06kx7jMpr1ILhMeCeV3b4eAJqkixjIMxXfaKyhjUXF5HsQ8KMfp9sf9n
        +0RZqu7uTb1Ckx3L4tRy2pQHyA3v9dBijkKBbq2Kl/yfxp1FWOuPhG/ELjTjMXZ8
        jLy2kW2L96SkaAZjQsMy5/nr12JrR2PetOnhzgbH91nc73XVpMMdGsB2+L8lTbYi
        lN/bB7zNxHVzeOXjmfaNHbxVoFIJZ6QN+34pHIxn0Deoc/qx/KW6/gCRKPqwfhXw
        JxtkWjoUV85bb8Idktv1H2ManU1DcDPZPMRj47MixOCU2tR9qpLMdbhGm8XVyWIz
        LxeCcaCgKOUn4NnjaMnP6awacx+lXSYyj68dRoI1ixLAc4Dz6NGt7B3JKM/DZTbS
        XgEohkNS4bBnlROIzUl48hBSv3kp4QAjPEmtDLB3hva3M8DCkeg5kCecK2sfBrFH
        ZGhqwaW9atOE6utTcEynFYwnkfTZ5SS5Y9w0Bq7XElQaZ3NNODtMeTzCj9q+Hiw=
        =y5kg
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
