apiVersion: v1
kind: Secret
metadata:
  name: tududi-secret
stringData:
  TUDUDI_USER_EMAIL: ENC[AES256_GCM,data:yOmFSJOKgsOXzZldaA==,iv:mG9y1Cu6phYJqX51LJVmcLKvey1nwU+N2wtf2zCvpPI=,tag:UgdSkfLglARHYiw/sc/lzg==,type:str]
  TUDUDI_USER_PASSWORD: ENC[AES256_GCM,data:BLMZy4QBgGPsFgaR9wYr5lHX9uqIAHgD9wgaXvDsIhA=,iv:Cvb/ULUGJQ7+AjcZTDAa27uSQ/v3rVVxRCgkk9bg/sQ=,tag:2TkpAHaeTaBvnxUNjhgeww==,type:str]
  TUDUDI_SESSION_SECRET: ENC[AES256_GCM,data:egWe+9s9Of8My/9ZNb/5u8xnXhstEAp6BF6vt8yzqQwuyLJutip5dOFTtKCbfyEF/qbm+3aK1DZ3iTqSMLc2HmZasroCK8YC2L6biaD0EZ20PLPSoj4KThKIyoqzpv6owOhFDPyXWBehy4gS/17dzXfrtX2Vrg2I+M0hYrcCMes=,iv:lqEEmcL/4+ZdvFVgxVe2nv5Q5SQcJppo1wCByFcQxvg=,tag:20mnDzCUwpj46eNdFl7ttg==,type:str]
sops:
  lastmodified: "2026-01-02T17:36:02Z"
  mac: ENC[AES256_GCM,data:wlEx9UjRUhoaiY5Y0EAliFeuxyKElFIeJqrmIDj006P9zm4UGJRaXtZpwZ13v7dnEXe8sMzbE/aUoresd4r/kg3Qsg//6OG9BJiPxYsaUyhKzzVlA6wK1W6MeOqXpZOKX83W3CfhiCxf4MbJsDR08Snw/GTi2mRPrWwz23vMeNA=,iv:+Yk+3AkUcRzxjjwmIcY9K0vcYN9a/TE0ll3Mf0AjMtw=,tag:zUM/28efe8TxRCJfCgowPg==,type:str]
  pgp:
    - created_at: "2025-12-30T21:41:20Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAj1mQBzs75ytiVmbeCndz2+Fgt1SmamO4kTQcQm55xlNk
        vuGUVFFjoa+KESboYxqGxEmyrjMrjN2RDxciBeJCPs3xgAfksoRN34VNeeR76hL4
        HZKi4uSMepgAqHTwFFyCaMo8jliHnM7bQsljf3P0mius0uJgmPaB5g7cdd7Sn9U0
        RxquvZx+V8tP1hdaQe+teaiwaNutChqwrsLk7k+qKADCbdtBvmXEGuyASS158ekk
        2v/5PhhqLmCS6IU+Jo1OH2rBbtKUpeoDIy9i22kwWoSRkHUmlD9z52/AvO/Zzu/9
        ZU8yVNgN06kx7jMpr1ILhMeCeV3b4eAJqkixjIMxXfaKyhjUXF5HsQ8KMfp9sf9n
        +0RZqu7uTb1Ckx3L4tRy2pQHyA3v9dBijkKBbq2Kl/yfxp1FWOuPhG/ELjTjMXZ8
        jLy2kW2L96SkaAZjQsMy5/nr12JrR2PetOnhzgbH91nc73XVpMMdGsB2+L8lTbYi
        lN/bB7zNxHVzeOXjmfaNHbxVoFIJZ6QN+34pHIxn0Deoc/qx/KW6/gCRKPqwfhXw
        JxtkWjoUV85bb8Idktv1H2ManU1DcDPZPMRj47MixOCU2tR9qpLMdbhGm8XVyWIz
        LxeCcaCgKOUn4NnjaMnP6awacx+lXSYyj68dRoI1ixLAc4Dz6NGt7B3JKM/DZTbS
        XgEohkNS4bBnlROIzUl48hBSv3kp4QAjPEmtDLB3hva3M8DCkeg5kCecK2sfBrFH
        ZGhqwaW9atOE6utTcEynFYwnkfTZ5SS5Y9w0Bq7XElQaZ3NNODtMeTzCj9q+Hiw=
        =y5kg
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
