apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "./namespace.yaml"
  - "./homarr/ks.yaml"
  - "./immich/ks.yaml"
  - "./paperless/ks.yaml"
  - "./memos/ks.yaml"
  - "./grist/ks.yaml"
  - "./n8n/ks.yaml"
  - "./rxresume/ks.yaml"
  - "./stirling-pdf/ks.yaml"
  - "./it-tools/ks.yaml"
  - "./teable/ks.yaml"
  - "./opencloud/ks.yaml"
  - "./ollama/ks.yaml"
  - "./openwebui/ks.yaml"
  - "./vaultwarden/ks.yaml"
  - "./mathesar/ks.yaml"
  - "./super-productivity/ks.yaml"
  - "./donetick/ks.yaml"
  - "./tududi/ks.yaml"
  - "./vikunja/ks.yaml"
