apiVersion: v1
kind: Secret
metadata:
  name: super-productivity-secret
stringData:
  WEBDAV_BASE_URL: ENC[AES256_GCM,data:QPpmrNBDh83F//jJ5O1b/MLc/hjDh/04pxdD1yZuVpp4NO3eujNk2lW2vrXtVVZTAHS9HMG5sAKODz/+6moVEi5IOhhC5FR2agoKqXuoHxAC6JiW0dieRVSlbV2dv1NxjxpoLQ6b2c0vL3TROabf1dqTqLwnyfcF1Qdnr63nrUuMPADv,iv:R9u1INmhhZRTaVRN/uZwlICzruPz8l2CHuloWXre1XA=,tag:jSSfFu2bdjFIeIuiAXJRhg==,type:str]
  WEBDAV_USERNAME: ENC[AES256_GCM,data:H8V1,iv:r0bHpaCY6K/3EwTTLZ2DSypZepLPzbYkUmOs1FeLxLI=,tag:1WxLZKOgmQdBjIZuS+XpiA==,type:str]
sops:
  lastmodified: "2025-12-21T17:13:50Z"
  mac: ENC[AES256_GCM,data:cvkJz9Jsy5Mv5NaXz04JvC5GG+stE/mmdH186Ljl50cgrAgseWp7/UCNN65KFSzCEsbbFVNdMMNofYRCwEV3DX7vza7cjIz4PW8NhzsP6NsNt5OXAtkEmYHTIjo0rVJveQmMNCgmuUqszYUq5+DtnPXCtBV0u3y3tQnSc937HEA=,iv:lqwEYES6sJhyeFzR6gDzQhbzzoYftn+GQG7yzYLKNDo=,tag:P1OztKiotXyn4iVLeX7DvA==,type:str]
  pgp:
    - created_at: "2025-08-12T14:08:37Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAjJO1d0laKZOvpdXRf8OGGK8ZI5XEPfUQaZ916rCuQdv1
        aOuonuJSEMoUQyJ1L3mogR5R3GijZeTz4PtILSPhmGoBtd4SDhoXE1xdk00dQQ2c
        YVRBegnBSi2+ofaCU2oZvwiM5Ut5TcmsB3DewNuFsa8GMh/OSDyru/dbPm7A/WQc
        /67/OunSn939yvaLvN7U7MGyJdlZnAdtf9+vhifFJWOfvbmcwV6cpkg2bSczSdwc
        bGn3S2O90wv4AgSACyf1QgfmqenRhQoQy3GrFC8Uco5F46QPRz/lOhbdm7aWw1IB
        dIEF7RIZ2Efyswl8oQXxRkOlTuFV3sCbxRTD+POeW4OmyWO/326JAnmRUzU35bQL
        ISp+Db7X5dpJ9Gn9E47ze/dYqnltfHcjGZzFV836/OgvLA4Tu9uYxNplXnA0MGFu
        25X+deN0HxRTil2YyWsvPHjwWPwlOV9ab7119zKwAatTQkIPt3xBpXjiOmDCO5Xd
        BAJWxgJY66ns9kXqbP73jP6NbKXLSM8Uju12+NIkogD3F6gtOSDnw34soCVT5/p8
        dPqXPXHIdaDT6ASSZPoHW8IGIxQMwqNZjZcW8czHvzSn8k7sjwO5kDewQmb+xFBG
        WTVU45ZmYO4cnuj39IcFTl9Eb7bvZ32DWb250KVqAaUTEWarO3tdVxwTQFA2nSLS
        XAGMPRcOnhlNRI2ZmfFtl7irro3fC56SHgav1/ApcSMb+UpL7QbalTcKbwEkOZcl
        mmPYFP2YjdCHqAGCmLoF4WljYS6cGTFFYqqkaiW8VkygxEV2K/0W6DO2Gvxa
        =uMlZ
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
